### valid
POST http://localhost:3001/api/user/login
content-type: application/json

{
    "name": "jota",
    "password": "samplepw"
}

### no pw or name
POST http://localhost:3001/api/user/login
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6ImpvdGEiLCJwYXNzd29yZCI6InNhbXBsZXB3IiwiaWF0IjoxNjU1MDA1MTI2fQ.UkQzI5NOyAq3PaNL8-qw5Vh_8078WHgfzkLn8GCemAA

{
    "name": "jota",
    "password": "samplepw"
}